package com.ktxconverter.app

object EtcDecoder {
    val ETC_MODIFIER_TABLES = arrayOf(intArrayOf(2,8,-2,-8),intArrayOf(5,17,-5,-17),intArrayOf(9,29,-9,-29),intArrayOf(13,42,-13,-42),intArrayOf(18,60,-18,-60),intArrayOf(24,80,-24,-80),intArrayOf(33,106,-33,-106),intArrayOf(47,183,-47,-183))
    val EAC_MODIFIER_TABLES = arrayOf(intArrayOf(-3,-6,-9,-15,2,5,8,14),intArrayOf(-3,-7,-10,-13,2,6,9,12),intArrayOf(-2,-5,-8,-13,1,4,7,12),intArrayOf(-2,-4,-6,-13,1,3,5,12),intArrayOf(-3,-6,-8,-12,2,5,7,11),intArrayOf(-3,-7,-9,-11,2,6,8,10),intArrayOf(-4,-7,-8,-11,3,6,7,10),intArrayOf(-3,-5,-8,-11,2,4,7,10),intArrayOf(-2,-6,-8,-10,1,5,7,9),intArrayOf(-2,-5,-8,-10,1,4,7,9),intArrayOf(-2,-4,-8,-10,1,3,7,9),intArrayOf(-2,-5,-7,-10,1,4,6,9),intArrayOf(-3,-4,-7,-10,2,3,6,9),intArrayOf(-1,-2,-3,-10,0,1,2,9),intArrayOf(-4,-6,-8,-9,3,5,7,8),intArrayOf(-3,-5,-7,-9,2,4,6,8))
    fun clampByte(v:Int)=v.coerceIn(0,255)
    fun extend4bit(v:Int)=(v shl 4) or v
    fun extend5bit(v:Int)=(v shl 3) or (v shr 2)
    fun signExtend3bit(v:Int)=if((v and 4)!=0) v-8 else v
    fun decodeEtc2Block(blockBytes:ByteArray,offset:Int=0):ByteArray{val hi=((blockBytes[offset].toInt()and 0xFF)shl 24)or((blockBytes[offset+1].toInt()and 0xFF)shl 16)or((blockBytes[offset+2].toInt()and 0xFF)shl 8)or(blockBytes[offset+3].toInt()and 0xFF);val lo=((blockBytes[offset+4].toInt()and 0xFF)shl 24)or((blockBytes[offset+5].toInt()and 0xFF)shl 16)or((blockBytes[offset+6].toInt()and 0xFF)shl 8)or(blockBytes[offset+7].toInt()and 0xFF);val diffbit=(hi ushr 31)and 1;val flipbit=(hi ushr 30)and 1;val cw2=(hi ushr 27)and 7;val cw1=(hi ushr 24)and 7;val color1:Triple<Int,Int,Int>;val color2:Triple<Int,Int,Int>;if(diffbit==0){val b2=(hi ushr 20)and 0xF;val g2=(hi ushr 16)and 0xF;val r2=(hi ushr 12)and 0xF;val b1=(hi ushr 8)and 0xF;val g1=(hi ushr 4)and 0xF;val r1=hi and 0xF;color1=Triple(extend4bit(r1),extend4bit(g1),extend4bit(b1));color2=Triple(extend4bit(r2),extend4bit(g2),extend4bit(b2))}else{val db=(hi ushr 21)and 0x7;val dg=(hi ushr 18)and 0x7;val dr=(hi ushr 15)and 0x7;val rBase=hi and 0x1F;val gBase=(hi ushr 5)and 0x1F;val bBase=(hi ushr 10)and 0x1F;color1=Triple(extend5bit(rBase),extend5bit(gBase),extend5bit(bBase));color2=Triple(clampByte(extend5bit(rBase+signExtend3bit(dr))),clampByte(extend5bit(gBase+signExtend3bit(dg))),clampByte(extend5bit(bBase+signExtend3bit(db))))};val pixels=ByteArray(48);val table1=ETC_MODIFIER_TABLES[cw1];val table2=ETC_MODIFIER_TABLES[cw2];for(py in 0..3)for(px in 0..3){val pixelIdx=py*4+px;val useColor2=if(flipbit==0)py>=2 else px>=2;val lsb=(lo ushr pixelIdx)and 1;val msb=(lo ushr(pixelIdx+16))and 1;val pixIdx=(msb shl 1)or lsb;val table=if(useColor2)table2 else table1;val modifier=table[pixIdx];val base=if(useColor2)color2 else color1;pixels[pixelIdx*3+0]=clampByte(base.first+modifier).toByte();pixels[pixelIdx*3+1]=clampByte(base.second+modifier).toByte();pixels[pixelIdx*3+2]=clampByte(base.third+modifier).toByte()};return pixels}
    fun decodeEacBlock(blockBytes:ByteArray,offset:Int=0):IntArray{val hi=((blockBytes[offset+3].toInt()and 0xFF)shl 24)or((blockBytes[offset+2].toInt()and 0xFF)shl 16)or((blockBytes[offset+1].toInt()and 0xFF)shl 8)or(blockBytes[offset].toInt()and 0xFF);val lo=((blockBytes[offset+7].toInt()and 0xFF)shl 24)or((blockBytes[offset+6].toInt()and 0xFF)shl 16)or((blockBytes[offset+5].toInt()and 0xFF)shl 8)or(blockBytes[offset+4].toInt()and 0xFF);val base=(hi ushr 24)and 0xFF;val multVal=(hi ushr 20)and 0xF;val tableIdx=(hi ushr 16)and 0xF;val mult=multVal+1;val modifiers=EAC_MODIFIER_TABLES[tableIdx];val combined=((hi.toLong()and 0xFFFF)shl 32)or(lo.toLong()and 0xFFFFFFFFL);val alphas=IntArray(16);for(i in 0..15){val pixIdx=((combined ushr(i*3))and 0x7).toInt();alphas[i]=clampByte(base+modifiers[pixIdx]*mult)};return alphas}
    fun decodeEtc2Rgb(data:ByteArray,w:Int,h:Int):ByteArray{val bx=(w+3)/4;val by=(h+3)/4;val pixels=ByteArray(w*h*4);for(byi in 0..<by)for(bxi in 0..<bx){val rgb=decodeEtc2Block(data,(byi*bx+bxi)*8);for(py in 0..3)for(px in 0..3){val x=bxi*4+px;val y=byi*4+py;if(x>=w||y>=h)continue;val dst=(y*w+x)*4;val src=(py*4+px)*3;pixels[dst]=rgb[src];pixels[dst+1]=rgb[src+1];pixels[dst+2]=rgb[src+2];pixels[dst+3]=255.toByte()}};return pixels}
    fun decodeEtc2Rgba(data:ByteArray,w:Int,h:Int):ByteArray{val bx=(w+3)/4;val by=(h+3)/4;val pixels=ByteArray(w*h*4);for(byi in 0..<by)for(bxi in 0..<bx){val off=(byi*bx+bxi)*16;val rgb=decodeEtc2Block(data,off+8);val alphas=decodeEacBlock(data,off);for(py in 0..3)for(px in 0..3){val x=bxi*4+px;val y=byi*4+py;if(x>=w||y>=h)continue;val dst=(y*w+x)*4;val src=(py*4+px)*3;pixels[dst]=rgb[src];pixels[dst+1]=rgb[src+1];pixels[dst+2]=rgb[src+2];pixels[dst+3]=alphas[py*4+px].toByte()}};return pixels}
    fun decodeR11Eac(data:ByteArray,w:Int,h:Int):ByteArray{val bx=(w+3)/4;val by=(h+3)/4;val pixels=ByteArray(w*h*4);for(byi in 0..<by)for(bxi in 0..<bx){val alphas=decodeEacBlock(data,(byi*bx+bxi)*8);for(py in 0..3)for(px in 0..3){val x=bxi*4+px;val y=byi*4+py;if(x>=w||y>=h)continue;val dst=(y*w+x)*4;val v=alphas[py*4+px].toByte();pixels[dst]=v;pixels[dst+1]=v;pixels[dst+2]=v;pixels[dst+3]=255.toByte()}};return pixels}
    fun decodeRg11Eac(data:ByteArray,w:Int,h:Int):ByteArray{val bx=(w+3)/4;val by=(h+3)/4;val pixels=ByteArray(w*h*4);for(byi in 0..<by)for(bxi in 0..<bx){val off=(byi*bx+bxi)*16;val rV=decodeEacBlock(data,off);val gV=decodeEacBlock(data,off+8);for(py in 0..3)for(px in 0..3){val x=bxi*4+px;val y=byi*4+py;if(x>=w||y>=h)continue;val dst=(y*w+x)*4;pixels[dst]=rV[py*4+px].toByte();pixels[dst+1]=gV[py*4+px].toByte();pixels[dst+2]=0;pixels[dst+3]=255.toByte()}};return pixels}
    fun decodeRawPixels(raw:ByteArray,w:Int,h:Int,gf:Int,gt:Int):ByteArray{val pixels=ByteArray(w*h*4);val n=w*h;if(gt==KtxParser.GL_UNSIGNED_BYTE){when(gf){KtxParser.GL_RGBA->{for(i in 0..<n){val s=i*4;pixels[i*4]=raw[s];pixels[i*4+1]=raw[s+1];pixels[i*4+2]=raw[s+2];pixels[i*4+3]=raw[s+3]}};KtxParser.GL_RGB->{for(i in 0..<n){pixels[i*4]=raw[i*3];pixels[i*4+1]=raw[i*3+1];pixels[i*4+2]=raw[i*3+2];pixels[i*4+3]=255.toByte()}};KtxParser.GL_RED->{for(i in 0..<n){val v=raw[i];pixels[i*4]=v;pixels[i*4+1]=v;pixels[i*4+2]=v;pixels[i*4+3]=255.toByte()}};KtxParser.GL_RG->{for(i in 0..<n){pixels[i*4]=raw[i*2];pixels[i*4+1]=raw[i*2+1];pixels[i*4+2]=0;pixels[i*4+3]=255.toByte()}};else->throw IllegalArgumentException("unsupported glFormat")}}else if(gt==KtxParser.GL_UNSIGNED_SHORT){val buf=java.nio.ByteBuffer.wrap(raw).order(java.nio.ByteOrder.LITTLE_ENDIAN);if(gf==KtxParser.GL_RGBA)for(i in 0..<n){val o=i*8;pixels[i*4]=(buf.getShort(o).toInt()and 0xFFFF shr 8).toByte();pixels[i*4+1]=(buf.getShort(o+2).toInt()and 0xFFFF shr 8).toByte();pixels[i*4+2]=(buf.getShort(o+4).toInt()and 0xFFFF shr 8).toByte();pixels[i*4+3]=(buf.getShort(o+6).toInt()and 0xFFFF shr 8).toByte()}}else throw IllegalArgumentException("unsupported glType");return pixels}
}
